import type { Event } from "@/types/event";

export const sampleEvents: Event[] = [
  {
    id: "1",
    title: "🔥 焼肉食べ放題いきませんか！",
    restaurant: "焼肉きんぐ 新宿西口ビックカメラ店",
    address: "東京都新宿区西新宿1-xx-xx",
    date: "3/20（木）",
    time: "19:00",
    area: "新宿",
    category: "焼肉",
    subCategory: "ホルモン",
    budget: "3,000〜4,000円",
    currentMembers: 2,
    maxMembers: 4,
    genderFilter: "anyone",
    status: "recruiting",
    host: {
      nickname: "たけし",
      ageGroup: "30代",
      gender: "男性",
      trustScore: 4.8,
    },
    participants: [{ nickname: "ゆうき", ageGroup: "20代", gender: "男性" }],
  },
  {
    id: "2",
    title: "🍣 回転寿司で飲みましょう",
    restaurant: "スシロー 渋谷駅前店",
    address: "東京都渋谷区道玄坂2-xx-xx",
    date: "3/22（土）",
    time: "18:30",
    area: "渋谷",
    category: "寿司",
    subCategory: "回転寿司",
    budget: "2,000〜3,000円",
    currentMembers: 1,
    maxMembers: 3,
    genderFilter: "anyone",
    status: "recruiting",
    host: {
      nickname: "あやか",
      ageGroup: "20代",
      gender: "女性",
      trustScore: 5.0,
    },
    participants: [],
  },
  {
    id: "3",
    title: "🍲 火鍋でわいわい飲みたい",
    restaurant: "海底撈火鍋 池袋店",
    address: "東京都豊島区東池袋1-xx-xx",
    date: "3/25（火）",
    time: "19:30",
    area: "池袋",
    category: "中華",
    subCategory: "火鍋",
    budget: "4,000〜5,000円",
    currentMembers: 4,
    maxMembers: 5,
    genderFilter: "female",
    status: "recruiting",
    host: {
      nickname: "みさき",
      ageGroup: "20代",
      gender: "女性",
      trustScore: 4.5,
    },
    participants: [
      { nickname: "はるか", ageGroup: "20代", gender: "女性" },
      { nickname: "さくら", ageGroup: "30代", gender: "女性" },
      { nickname: "ゆい", ageGroup: "20代", gender: "女性" },
    ],
  },
  {
    id: "4",
    title: "🍕 イタリアンで女子会",
    restaurant: "サルヴァトーレ クオモ 恵比寿",
    address: "東京都渋谷区恵比寿南1-xx-xx",
    date: "3/28（金）",
    time: "19:00",
    area: "恵比寿",
    category: "イタリアン",
    subCategory: "ピザ",
    budget: "5,000〜6,000円",
    currentMembers: 5,
    maxMembers: 5,
    genderFilter: "female",
    status: "confirmed",
    host: {
      nickname: "まい",
      ageGroup: "30代",
      gender: "女性",
      trustScore: 4.9,
    },
    participants: [
      { nickname: "りな", ageGroup: "20代", gender: "女性" },
      { nickname: "かな", ageGroup: "30代", gender: "女性" },
      { nickname: "えり", ageGroup: "20代", gender: "女性" },
      { nickname: "あい", ageGroup: "30代", gender: "女性" },
    ],
  },
  {
    id: "5",
    title: "🍺 大衆酒場でサク飲み",
    restaurant: "もつ焼き でん 新橋店",
    address: "東京都港区新橋3-xx-xx",
    date: "3/21（金）",
    time: "18:00",
    area: "新橋",
    category: "居酒屋",
    subCategory: "大衆酒場",
    budget: "2,000〜3,000円",
    currentMembers: 2,
    maxMembers: 4,
    genderFilter: "anyone",
    status: "recruiting",
    host: {
      nickname: "けんじ",
      ageGroup: "40代",
      gender: "男性",
      trustScore: 4.2,
    },
    participants: [{ nickname: "ひろし", ageGroup: "40代", gender: "男性" }],
  },
];
